version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
    networks:
      - app-network

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret123"
      MYSQL_USER: "developer"
      MYSQL_PASSWORD: "secret123"
      MYSQL_DATABASE: "developmentdb"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3406:3306
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
      - UPLOAD_LIMIT=300M
    networks:
      - app-network

volumes:
  mysqldata: {}

networks:
  app-network:
